---
name: Build and test inspec-reporter-json-hdf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-10.15, windows-latest ]
        ruby: [ 2.7 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Fetch all tags for versioning
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler and git-version-bump
        run: gem install bundler git-version-bump
      - name: Run bundle install
        run: bundle install
      - name: Run rake unit tests
        run: bundle exec rake unit
      - name: Run bundle-audit
        run: bundle-audit check --update
      - name: Build inspec-reporter-json-hdf gem
        run: gem build inspec-reporter-json-hdf.gemspec
      - name: Install Inspec 
        run: gem install inspec inspec-bin
      - name: Install Inspec plugin
        run: inspec plugin install inspec-reporter-json-hdf-*.gem
        env:
          CHEF_LICENSE: "accept"
      - name: Generate attestation file
        run: ruby test/generate_attestation_file.rb
      - name: Run inspec with attestations
        run: inspec exec test/test-profile/ --reporter hdf:test_hdf.json --config attestations.json || true
        env:
          CHEF_LICENSE: "accept"
      - name: Run rake functional tests
        run: bundle exec rake functional
